
export const skills=[
    {
        id:1,
        img_src:"https://cdn2.iconfinder.com/data/icons/strongicon-vol-24-free/24/filetype-16-64.png",
        skill:"C++",
        per:90,
    },
    {
        id:2,
        img_src:"https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/181_Java_logo_logos-64.png",
        skill:"Java",
        per:95,
    },
    {
        id:3,
        img_src:"https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/187_Js_logo_logos-512.png",
        skill:"Javascript",
        per:95,
    },
    {
        id:4,
        img_src:"https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/267_Python_logo-64.png",
        skill:"Python",
        per:70,
    },
    {
        id:5,
        img_src:"https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/256_Php_logo-64.png",
        skill:"Php",
        per:75,
    },
    {
        id:6,
        img_src:"https://cdn4.iconfinder.com/data/icons/logos-3/600/React.js_logo-512.png",
        skill:"React.js",
        per:90,
    },
    
    {
        id:8,
        img_src:"https://cdn3.iconfinder.com/data/icons/teenyicons-solid-vol-3/15/typescript-64.png",
        skill:"TypeScript",
        per:80,
    },
   
    {
        id:10,
        img_src:"https://cdn4.iconfinder.com/data/icons/logos-3/512/mongodb-2-64.png",
        skill:"MongoDb",
        per:80,
    },
    {
        id:11,
        img_src:"https://cdn0.iconfinder.com/data/icons/flat-design-database-set-5/24/mysql-64.png",
        skill:"MySql",
        per:80,
    },
    
    {
        id:13,
        img_src:"https://cdn3.iconfinder.com/data/icons/social-media-2169/24/social_media_social_media_logo_git-64.png",
        skill:"Git/GitHub",
        per:90,
    },
    {
        id:14,
        img_src:"https://cdn4.iconfinder.com/data/icons/logos-brands-5/24/postman-64.png",
        skill:"Postman",
        per:80,
    },
    {
        id:9,
        img_src:"https://cdn2.iconfinder.com/data/icons/boxicons-logos/24/bxl-tailwind-css-64.png",
        skill:"Tailwind",
        per:85,
    },
    {
        id:12,
        img_src:"https://cdn3.iconfinder.com/data/icons/logos-brands-3/24/logo_brand_brands_logos_android-64.png",
        skill:"Android Studio",
        per:80,
    },
    {
        id:7,
        img_src:"https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/233_Node_Js_logo-64.png",
        skill:"Node.js/Express.js",
        per:90,
    },
]